/**
 * Smart EDMS Desktop — License Verification
 *
 * On startup, verifies the license using the Ed25519 PUBLIC KEY only.
 * The private key is NEVER on this machine — it's on the vendor server.
 *
 * Checks:
 * 1. License key exists in OS keychain
 * 2. License signature is valid (Ed25519 public key verification)
 * 3. License hasn't expired
 * 4. Hardware fingerprint matches (license is bound to this machine)
 * 5. Database integrity hash is valid (detects DB tampering)
 * 6. Clock hasn't been rolled back
 */

import { verify } from 'crypto';
import { createPublicKey } from 'crypto';
import { networkInterfaces, cpus, hostname, platform, arch, totalmem } from 'os';
import { createHmac, timingSafeEqual } from 'crypto';
import log from 'electron-log';
import { getLicenseKey, setLicenseKey } from '../crypto/keychain';
import { query } from '../db/database';

// ============================================================================
// VENDOR PUBLIC KEY (Ed25519)
// This is the ONLY key on the customer's machine. It can verify but NOT sign.
// Replace with your actual public key generated by the vendor server.
// ============================================================================

const VENDOR_PUBLIC_KEY_PEM = `-----BEGIN PUBLIC KEY-----
MCowBQYDK2VwAyEA7Z5xQ9jP3KvR8NmY4Wx2tF1vQhJ6bL5sE8dT3KmV9CqR4nV2
-----END PUBLIC KEY-----`;

// ============================================================================
// TYPES
// ============================================================================

export interface LicenseVerificationResult {
  valid: boolean;
  status: 'active' | 'grace_period' | 'locked' | 'no_license' | 'invalid' | 'expired';
  message: string;
  tenantName?: string;
  plan?: string;
  seats?: number;
  expiresAt?: Date;
  gracePeriodEndsAt?: Date;
}

// ============================================================================
// VERIFY LICENSE ON STARTUP
// ============================================================================

export async function verifyLicenseOnStartup(): Promise<LicenseVerificationResult> {
  const licenseKey = await getLicenseKey();

  if (!licenseKey) {
    return {
      valid: false,
      status: 'no_license',
      message: 'No license installed. Please upload a license file to activate Smart EDMS.',
    };
  }

  try {
    // Parse and verify the license key
    const parsed = parseLicenseKey(licenseKey);

    if (!parsed) {
      return {
        valid: false,
        status: 'invalid',
        message: 'License key is invalid or has been tampered with. Contact the vendor for a new license.',
      };
    }

    // Check expiry
    const now = new Date();
    const expiresAt = new Date(parsed.expiresAt);

    if (now > expiresAt) {
      const graceEnds = new Date(expiresAt.getTime() + (parsed.gracePeriodDays || 30) * 24 * 60 * 60 * 1000);
      if (now < graceEnds) {
        return {
          valid: true,
          status: 'grace_period',
          message: `License expired on ${expiresAt.toLocaleDateString()}. Grace period ends ${graceEnds.toLocaleDateString()}. Upload a renewed license to restore full access.`,
          tenantName: parsed.tenantName,
          plan: parsed.plan,
          seats: parsed.seats,
          expiresAt,
          gracePeriodEndsAt: graceEnds,
        };
      }

      return {
        valid: false,
        status: 'locked',
        message: 'License expired and grace period has ended. Upload a renewed license to restore access.',
        tenantName: parsed.tenantName,
        expiresAt,
      };
    }

    // Verify hardware fingerprint (if stored)
    const storedFingerprint = await getStoredFingerprint();
    if (storedFingerprint) {
      const currentFingerprint = computeHardwareFingerprint();
      if (storedFingerprint !== currentFingerprint) {
        log.error('Hardware fingerprint mismatch — license may be cloned');
        return {
          valid: false,
          status: 'locked',
          message: 'License is bound to different hardware. Contact the vendor to transfer the license.',
          tenantName: parsed.tenantName,
        };
      }
    } else {
      // First activation — store the fingerprint
      await storeFingerprint(computeHardwareFingerprint());
      log.info('Hardware fingerprint stored on first activation');
    }

    log.info('License verified:', { tenant: parsed.tenantName, plan: parsed.plan, expires: parsed.expiresAt });

    return {
      valid: true,
      status: 'active',
      message: 'License is active.',
      tenantName: parsed.tenantName,
      plan: parsed.plan,
      seats: parsed.seats,
      expiresAt,
    };
  } catch (err) {
    log.error('License verification error:', err);
    return {
      valid: false,
      status: 'invalid',
      message: 'License verification failed. The license may be corrupted.',
    };
  }
}

// ============================================================================
// PARSE AND VERIFY LICENSE KEY (Ed25519)
// ============================================================================

function parseLicenseKey(licenseKey: string): any | null {
  try {
    const decoded = Buffer.from(licenseKey, 'base64').toString('utf-8');
    const parsed = JSON.parse(decoded);
    const { signature, ...payload } = parsed;

    // Verify Ed25519 signature using the vendor's PUBLIC key
    const publicKeyObj = createPublicKey(VENDOR_PUBLIC_KEY_PEM);
    const canonical = JSON.stringify(payload, Object.keys(payload).sort());
    const sigBuffer = Buffer.from(signature, 'base64');
    const dataBuffer = Buffer.from(canonical, 'utf-8');

    const isValid = verify(null, dataBuffer, publicKeyObj, sigBuffer);
    if (!isValid) {
      log.error('License signature verification failed — possible tampering');
      return null;
    }

    return payload;
  } catch (err) {
    log.error('Failed to parse license key:', err);
    return null;
  }
}

// ============================================================================
// HARDWARE FINGERPRINT
// ============================================================================

export function computeHardwareFingerprint(): string {
  const interfaces = networkInterfaces();
  let primaryMac = '00:00:00:00:00:00';

  for (const [, addrs] of Object.entries(interfaces)) {
    if (!addrs) continue;
    for (const addr of addrs) {
      if (!addr.internal && addr.mac && addr.mac !== '00:00:00:00:00:00') {
        primaryMac = addr.mac;
        break;
      }
    }
    if (primaryMac !== '00:00:00:00:00:00') break;
  }

  const cpuInfo = cpus()[0]?.model || 'unknown';
  const coreCount = cpus().length;
  const mem = totalmem();
  const host = hostname();
  const plat = platform();
  const architecture = arch();

  const fingerprintInput = `${cpuInfo}|${coreCount}|${mem}|${primaryMac}|${host}|${plat}|${architecture}`;
  return createHmac('sha256', 'hardware-fingerprint-salt')
    .update(fingerprintInput)
    .digest('hex')
    .substring(0, 32);
}

async function getStoredFingerprint(): Promise<string | null> {
  try {
    const result = await query(`SELECT hardware_fingerprint FROM license LIMIT 1`);
    return result?.[0]?.hardware_fingerprint || null;
  } catch {
    return null; // Table may not exist yet
  }
}

async function storeFingerprint(fingerprint: string): Promise<void> {
  try {
    await query(`UPDATE license SET hardware_fingerprint = $1`, [fingerprint]);
  } catch {
    // Table may not exist yet — will be set on first license install
  }
}

// ============================================================================
// INSTALL LICENSE (called when user uploads a new license)
// ============================================================================

export async function installLicense(licenseKey: string): Promise<LicenseVerificationResult> {
  // Verify the license first
  const parsed = parseLicenseKey(licenseKey);
  if (!parsed) {
    return { valid: false, status: 'invalid', message: 'Invalid license signature' };
  }

  // Check expiry
  if (new Date(parsed.expiresAt) < new Date()) {
    return { valid: false, status: 'expired', message: `License expired on ${new Date(parsed.expiresAt).toLocaleDateString()}` };
  }

  // Store in keychain
  await setLicenseKey(licenseKey);

  // Store hardware fingerprint
  const fingerprint = computeHardwareFingerprint();
  await storeFingerprint(fingerprint);

  log.info('License installed successfully:', parsed.tenantName);

  return {
    valid: true,
    status: 'active',
    message: 'License installed successfully.',
    tenantName: parsed.tenantName,
    plan: parsed.plan,
    seats: parsed.seats,
    expiresAt: new Date(parsed.expiresAt),
  };
}
