#!/usr/bin/env python3
"""
Smart EDMS — Add `emails` and `notifications` namespaces to all 5 locale files.

Adds enterprise-grade i18n bundles for:
  - emails.* (8 templates x 5 locales)
  - notifications.* (16 templates x 5 locales)

Each template uses ICU-style placeholders {name}, {count}, etc.

Run: python3 scripts/add-email-notif-i18n.py
"""

import json
import os
import sys
from pathlib import Path

MESSAGES_DIR = Path(__file__).parent.parent / "messages"

# ------------------------------------------------------------------
#  EMAIL BUNDLES — 8 templates x 5 locales
# ------------------------------------------------------------------

EMAILS = {
    "en": {
        "emails": {
            "common": {
                "appName": "Smart EDMS",
                "tagline": "Secure Document Governance Platform",
                "footer": "This is an automated message. Do not reply.",
                "footerAddress": "Smart EDMS — Secure Document Governance Platform",
                "unsubscribe": "Manage notification preferences",
                "privacyNotice": "You receive this email because you have an account on Smart EDMS. If you believe this is an error, contact your administrator.",
                "autoGenerated": "Automated message — please do not reply directly to this email.",
                "linkHelpText": "If the button above does not work, copy and paste this link into your browser:",
                "expiresIn": "This link expires in {duration}.",
                "viewInBrowser": "View in browser",
            },
            "invitation": {
                "subject": "Invitation to {tenantName} on Smart EDMS",
                "title": "You're invited",
                "heading": "You've been invited to {tenantName}",
                "body": "<strong>{inviterEmail}</strong> has invited you to join Smart EDMS at <strong>{tenantName}</strong>.",
                "cta": "Accept invitation",
                "expiresNote": "Your invitation expires in 7 days.",
                "welcome": "Smart EDMS is a secure enterprise document management platform with classification, workflow, retention, and audit-trail capabilities.",
            },
            "failedLogin": {
                "subject": "[Smart EDMS] {count} failed login attempts",
                "title": "Failed login attempts",
                "heading": "Failed login attempts on your account",
                "alert": "<strong>{count}</strong> failed login attempt(s) were recorded on your Smart EDMS account.",
                "ipLabel": "IP address",
                "advice": "If this was not you, consider changing your password immediately and enabling MFA if you haven't already.",
                "lockWarning": "Your account will be temporarily locked after 5 failed attempts.",
                "text": "{count} failed login attempts on your account from IP {ip}.\n\nIf this was not you, change your password and enable MFA.",
            },
            "accountLocked": {
                "subject": "[Smart EDMS] Account locked: {email}",
                "title": "Account locked",
                "heading": "Account locked",
                "alert": "The account <strong>{email}</strong> has been locked after 5 failed login attempts.",
                "ipLabel": "IP address",
                "advice": "The account will be automatically unlocked after 15 minutes. If you believe this is an attack, contact your administrator immediately.",
                "text": "Account {email} locked after 5 failed logins from {ip}. Auto-unlocks in 15 minutes.",
            },
            "breakGlass": {
                "subject": "[Smart EDMS] ⚠️ Break-glass access by {userEmail}",
                "title": "⚠️ Break-glass access granted",
                "heading": "Break-glass emergency access granted",
                "alert": "<strong>{userEmail}</strong> was granted emergency administrative access.",
                "userLabel": "User",
                "reasonLabel": "Reason",
                "expiresLabel": "Expires",
                "reviewAdvice": "All actions taken during this session are audit-logged with break-glass attribution. Please review the audit trail after the session expires.",
                "text": "Break-glass access granted to {userEmail}. Reason: {reason}. Expires: {expiresAt}. Review audit trail.",
            },
            "workflowAssigned": {
                "subject": "[Smart EDMS] Approval requested: {documentTitle}",
                "title": "Approval requested",
                "heading": "You have a document to approve",
                "body": "An approval has been assigned to you in Smart EDMS.",
                "documentLabel": "Document",
                "workflowLabel": "Workflow",
                "cta": "Review & approve",
                "text": "Approval requested for \"{documentTitle}\" ({workflowName}).\n\nReview: {workflowUrl}",
            },
            "shareNotification": {
                "subject": "[Smart EDMS] Document shared: {documentTitle}",
                "title": "Document shared with you",
                "heading": "A document has been shared with you",
                "body": "<strong>{sharedBy}</strong> shared a document with you on Smart EDMS.",
                "documentLabel": "Document",
                "cta": "View document",
                "expiresNote": "This share link expires on {expiresAt}.",
                "text": "{sharedBy} shared \"{documentTitle}\" with you.\n\nView: {shareUrl}",
            },
            "dispositionApproval": {
                "subject": "[Smart EDMS] Disposition approval: {documentTitle}",
                "title": "Disposition approval required",
                "heading": "Disposition approval required",
                "alert": "A document is pending <strong>{actionLabel}</strong> disposition and requires your approval.",
                "documentLabel": "Document",
                "actionLabel": "Action",
                "cta": "Review disposition",
                "text": "Disposition approval required for \"{documentTitle}\" (action: {action}).\n\nReview: {url}",
                "actions": {
                    "delete": "Delete",
                    "archive": "Archive",
                    "review": "Review",
                },
            },
            "passwordReset": {
                "subject": "[Smart EDMS] Password reset",
                "title": "Password reset",
                "heading": "Password reset request",
                "body": "We received a request to reset your Smart EDMS password.",
                "alert": "This link expires in 30 minutes. If you didn't request this, you can safely ignore this email.",
                "cta": "Reset password",
                "text": "Password reset request.\n\nReset your password: {resetUrl}\n\nThis link expires in 30 minutes.",
            },
        }
    },
    "fr": {
        "emails": {
            "common": {
                "appName": "Smart EDMS",
                "tagline": "Plateforme de gouvernance sécurisée des documents",
                "footer": "Ceci est un message automatique. Ne pas répondre.",
                "footerAddress": "Smart EDMS — Plateforme de gouvernance sécurisée des documents",
                "unsubscribe": "Gérer les préférences de notification",
                "privacyNotice": "Vous recevez cet e-mail car vous disposez d'un compte Smart EDMS. Si vous pensez qu'il s'agit d'une erreur, contactez votre administrateur.",
                "autoGenerated": "Message automatique — merci de ne pas répondre directement à cet e-mail.",
                "linkHelpText": "Si le bouton ci-dessus ne fonctionne pas, copiez et collez ce lien dans votre navigateur :",
                "expiresIn": "Ce lien expire dans {duration}.",
                "viewInBrowser": "Voir dans le navigateur",
            },
            "invitation": {
                "subject": "Invitation à {tenantName} sur Smart EDMS",
                "title": "Vous êtes invité",
                "heading": "Vous avez été invité à rejoindre {tenantName}",
                "body": "<strong>{inviterEmail}</strong> vous a invité à rejoindre Smart EDMS sur <strong>{tenantName}</strong>.",
                "cta": "Accepter l'invitation",
                "expiresNote": "Votre invitation expire dans 7 jours.",
                "welcome": "Smart EDMS est une plateforme sécurisée de gestion électronique des documents avec classification, flux de travail, conservation et piste d'audit.",
            },
            "failedLogin": {
                "subject": "[Smart EDMS] {count} tentatives de connexion échouées",
                "title": "Tentatives de connexion échouées",
                "heading": "Tentatives de connexion échouées sur votre compte",
                "alert": "<strong>{count}</strong> tentative(s) de connexion échouée(s) ont été enregistrées sur votre compte Smart EDMS.",
                "ipLabel": "Adresse IP",
                "advice": "Si ce n'était pas vous, envisagez de changer votre mot de passe immédiatement et d'activer l'authentification multifacteur si ce n'est pas déjà fait.",
                "lockWarning": "Votre compte sera temporairement verrouillé après 5 tentatives échouées.",
                "text": "{count} tentatives de connexion échouées sur votre compte depuis l'IP {ip}.\n\nSi ce n'était pas vous, changez votre mot de passe et activez l'MFA.",
            },
            "accountLocked": {
                "subject": "[Smart EDMS] Compte verrouillé : {email}",
                "title": "Compte verrouillé",
                "heading": "Compte verrouillé",
                "alert": "Le compte <strong>{email}</strong> a été verrouillé après 5 tentatives de connexion échouées.",
                "ipLabel": "Adresse IP",
                "advice": "Le compte sera automatiquement déverrouillé après 15 minutes. Si vous pensez qu'il s'agit d'une attaque, contactez immédiatement votre administrateur.",
                "text": "Compte {email} verrouillé après 5 tentatives échouées depuis {ip}. Déverrouillage automatique dans 15 minutes.",
            },
            "breakGlass": {
                "subject": "[Smart EDMS] ⚠️ Accès d'urgence par {userEmail}",
                "title": "⚠️ Accès d'urgence accordé",
                "heading": "Accès administratif d'urgence accordé",
                "alert": "<strong>{userEmail}</strong> a reçu un accès administratif d'urgence.",
                "userLabel": "Utilisateur",
                "reasonLabel": "Motif",
                "expiresLabel": "Expire",
                "reviewAdvice": "Toutes les actions effectuées pendant cette session sont journalisées avec attribution d'urgence. Veuillez examiner la piste d'audit après l'expiration de la session.",
                "text": "Accès d'urgence accordé à {userEmail}. Motif : {reason}. Expire : {expiresAt}. Examinez la piste d'audit.",
            },
            "workflowAssigned": {
                "subject": "[Smart EDMS] Approbation demandée : {documentTitle}",
                "title": "Approbation demandée",
                "heading": "Vous avez un document à approuver",
                "body": "Une approbation vous a été attribuée dans Smart EDMS.",
                "documentLabel": "Document",
                "workflowLabel": "Flux de travail",
                "cta": "Examiner et approuver",
                "text": "Approbation demandée pour « {documentTitle} » ({workflowName}).\n\nExaminer : {workflowUrl}",
            },
            "shareNotification": {
                "subject": "[Smart EDMS] Document partagé : {documentTitle}",
                "title": "Document partagé avec vous",
                "heading": "Un document a été partagé avec vous",
                "body": "<strong>{sharedBy}</strong> a partagé un document avec vous sur Smart EDMS.",
                "documentLabel": "Document",
                "cta": "Voir le document",
                "expiresNote": "Ce lien de partage expire le {expiresAt}.",
                "text": "{sharedBy} a partagé « {documentTitle} » avec vous.\n\nVoir : {shareUrl}",
            },
            "dispositionApproval": {
                "subject": "[Smart EDMS] Approbation de disposition : {documentTitle}",
                "title": "Approbation de disposition requise",
                "heading": "Approbation de disposition requise",
                "alert": "Un document est en attente de disposition <strong>{actionLabel}</strong> et nécessite votre approbation.",
                "documentLabel": "Document",
                "actionLabel": "Action",
                "cta": "Examiner la disposition",
                "text": "Approbation de disposition requise pour « {documentTitle} » (action : {action}).\n\nExaminer : {url}",
                "actions": {
                    "delete": "Supprimer",
                    "archive": "Archiver",
                    "review": "Examiner",
                },
            },
            "passwordReset": {
                "subject": "[Smart EDMS] Réinitialisation du mot de passe",
                "title": "Réinitialisation du mot de passe",
                "heading": "Demande de réinitialisation du mot de passe",
                "body": "Nous avons reçu une demande de réinitialisation de votre mot de passe Smart EDMS.",
                "alert": "Ce lien expire dans 30 minutes. Si vous n'avez pas fait cette demande, vous pouvez ignorer cet e-mail en toute sécurité.",
                "cta": "Réinitialiser le mot de passe",
                "text": "Demande de réinitialisation du mot de passe.\n\nRéinitialisez votre mot de passe : {resetUrl}\n\nCe lien expire dans 30 minutes.",
            },
        }
    },
    "ar": {
        "emails": {
            "common": {
                "appName": "Smart EDMS",
                "tagline": "منصة حوكمة آمنة للمستندات",
                "footer": "هذه رسالة آلية. لا ترد.",
                "footerAddress": "Smart EDMS — منصة حوكمة آمنة للمستندات",
                "unsubscribe": "إدارة تفضيلات الإشعارات",
                "privacyNotice": "تتلقى هذا البريد لأن لديك حساب على Smart EDMS. إذا كنت تعتقد أن هذا خطأ، اتصل بمسؤول النظام.",
                "autoGenerated": "رسالة آلية — يرجى عدم الرد مباشرة على هذا البريد.",
                "linkHelpText": "إذا لم يعمل الزر أعلاه، انسخ هذا الرابط والصقه في متصفحك:",
                "expiresIn": "تنتهي صلاحية هذا الرابط خلال {duration}.",
                "viewInBrowser": "عرض في المتصفح",
            },
            "invitation": {
                "subject": "دعوة إلى {tenantName} على Smart EDMS",
                "title": "دعوة",
                "heading": "تمت دعوتك إلى {tenantName}",
                "body": "دعاك <strong>{inviterEmail}</strong> للانضمام إلى Smart EDMS في <strong>{tenantName}</strong>.",
                "cta": "قبول الدعوة",
                "expiresNote": "تنتهي صلاحية الدعوة خلال 7 أيام.",
                "welcome": "Smart EDMS هي منصة آمنة لإدارة المستندات الإلكترونية مع تصنيف وسير عمل واحتفاظ وسجل تدقيق.",
            },
            "failedLogin": {
                "subject": "[Smart EDMS] {count} محاولات دخول فاشلة",
                "title": "محاولات دخول فاشلة",
                "heading": "محاولات دخول فاشلة على حسابك",
                "alert": "تم تسجيل <strong>{count}</strong> محاولة دخول فاشلة على حساب Smart EDMS الخاص بك.",
                "ipLabel": "عنوان IP",
                "advice": "إذا لم تكن أنت، فكر في تغيير كلمة المرور فوراً وتفعيل المصادقة متعددة العوامل.",
                "lockWarning": "سيتم قفل حسابك مؤقتاً بعد 5 محاولات فاشلة.",
                "text": "{count} محاولات دخول فاشلة من IP {ip}.\n\nإذا لم تكن أنت، غيّر كلمة المرور وفعّل MFA.",
            },
            "accountLocked": {
                "subject": "[Smart EDMS] تم قفل الحساب: {email}",
                "title": "تم قفل الحساب",
                "heading": "تم قفل الحساب",
                "alert": "تم قفل الحساب <strong>{email}</strong> بعد 5 محاولات دخول فاشلة.",
                "ipLabel": "عنوان IP",
                "advice": "سيتم فتح الحساب تلقائياً بعد 15 دقيقة. إذا كنت تعتقد أن هذا هجوم، اتصل بمسؤول النظام فوراً.",
                "text": "تم قفل الحساب {email} بعد 5 محاولات فاشلة من {ip}. يفتح تلقائياً خلال 15 دقيقة.",
            },
            "breakGlass": {
                "subject": "[Smart EDMS] ⚠️ وصول طارئ بواسطة {userEmail}",
                "title": "⚠️ تم منح الوصول الطارئ",
                "heading": "تم منح الوصول الإداري الطارئ",
                "alert": "تم منح <strong>{userEmail}</strong> وصولاً إدارياً طارئاً.",
                "userLabel": "المستخدم",
                "reasonLabel": "السبب",
                "expiresLabel": "ينتهي",
                "reviewAdvice": "جميع الإجراءات المتخذة خلال هذه الجلسة مسجلة في سجل التدقيق مع إسناد الوصول الطارئ. يرجى مراجعة سجل التدقيق بعد انتهاء الجلسة.",
                "text": "تم منح وصول طارئ لـ {userEmail}. السبب: {reason}. ينتهي: {expiresAt}. راجع سجل التدقيق.",
            },
            "workflowAssigned": {
                "subject": "[Smart EDMS] طلب موافقة: {documentTitle}",
                "title": "طلب موافقة",
                "heading": "لديك مستند للموافقة عليه",
                "body": "تم تعيين موافقة لك في Smart EDMS.",
                "documentLabel": "المستند",
                "workflowLabel": "سير العمل",
                "cta": "مراجعة وموافقة",
                "text": "طلب موافقة على \"{documentTitle}\" ({workflowName}).\n\nمراجعة: {workflowUrl}",
            },
            "shareNotification": {
                "subject": "[Smart EDMS] مستند مشترك: {documentTitle}",
                "title": "تمت مشاركة مستند معك",
                "heading": "تمت مشاركة مستند معك",
                "body": "شارك <strong>{sharedBy}</strong> مستنداً معك على Smart EDMS.",
                "documentLabel": "المستند",
                "cta": "عرض المستند",
                "expiresNote": "تنتهي صلاحية رابط المشاركة في {expiresAt}.",
                "text": "شارك {sharedBy} \"{documentTitle}\" معك.\n\nعرض: {shareUrl}",
            },
            "dispositionApproval": {
                "subject": "[Smart EDMS] موافقة على التصرف: {documentTitle}",
                "title": "مطلوب موافقة على التصرف",
                "heading": "مطلوب موافقة على التصرف",
                "alert": "مستند في انتظار تصرف <strong>{actionLabel}</strong> ويتطلب موافقتك.",
                "documentLabel": "المستند",
                "actionLabel": "الإجراء",
                "cta": "مراجعة التصرف",
                "text": "مطلوب موافقة على التصرف لـ \"{documentTitle}\" (إجراء: {action}).\n\nمراجعة: {url}",
                "actions": {
                    "delete": "حذف",
                    "archive": "أرشفة",
                    "review": "مراجعة",
                },
            },
            "passwordReset": {
                "subject": "[Smart EDMS] إعادة تعيين كلمة المرور",
                "title": "إعادة تعيين كلمة المرور",
                "heading": "طلب إعادة تعيين كلمة المرور",
                "body": "تلقينا طلباً لإعادة تعيين كلمة مرور Smart EDMS الخاصة بك.",
                "alert": "تنتهي صلاحية هذا الرابط خلال 30 دقيقة. إذا لم تطلب ذلك، يمكنك تجاهل هذا البريد بأمان.",
                "cta": "إعادة تعيين كلمة المرور",
                "text": "طلب إعادة تعيين كلمة المرور.\n\nأعد تعيين كلمة المرور: {resetUrl}\n\nتنتهي الصلاحية خلال 30 دقيقة.",
            },
        }
    },
    "es": {
        "emails": {
            "common": {
                "appName": "Smart EDMS",
                "tagline": "Plataforma segura de gobernanza de documentos",
                "footer": "Este es un mensaje automatizado. No responda.",
                "footerAddress": "Smart EDMS — Plataforma segura de gobernanza de documentos",
                "unsubscribe": "Gestionar preferencias de notificación",
                "privacyNotice": "Recibe este correo porque tiene una cuenta en Smart EDMS. Si cree que es un error, contacte con su administrador.",
                "autoGenerated": "Mensaje automatizado — por favor no responda directamente a este correo.",
                "linkHelpText": "Si el botón anterior no funciona, copie y pegue este enlace en su navegador:",
                "expiresIn": "Este enlace expira en {duration}.",
                "viewInBrowser": "Ver en el navegador",
            },
            "invitation": {
                "subject": "Invitación a {tenantName} en Smart EDMS",
                "title": "Está invitado",
                "heading": "Ha sido invitado a {tenantName}",
                "body": "<strong>{inviterEmail}</strong> le ha invitado a unirse a Smart EDMS en <strong>{tenantName}</strong>.",
                "cta": "Aceptar invitación",
                "expiresNote": "Su invitación expira en 7 días.",
                "welcome": "Smart EDMS es una plataforma segura de gestión documental con clasificación, flujos de trabajo, retención y auditoría.",
            },
            "failedLogin": {
                "subject": "[Smart EDMS] {count} intentos de inicio de sesión fallidos",
                "title": "Intentos de inicio de sesión fallidos",
                "heading": "Intentos de inicio de sesión fallidos en su cuenta",
                "alert": "Se registraron <strong>{count}</strong> intento(s) de inicio de sesión fallido(s) en su cuenta Smart EDMS.",
                "ipLabel": "Dirección IP",
                "advice": "Si no fue usted, considere cambiar su contraseña inmediatamente y habilitar MFA si aún no lo ha hecho.",
                "lockWarning": "Su cuenta se bloqueará temporalmente después de 5 intentos fallidos.",
                "text": "{count} intentos de inicio de sesión fallidos desde IP {ip}.\n\nSi no fue usted, cambie su contraseña y habilite MFA.",
            },
            "accountLocked": {
                "subject": "[Smart EDMS] Cuenta bloqueada: {email}",
                "title": "Cuenta bloqueada",
                "heading": "Cuenta bloqueada",
                "alert": "La cuenta <strong>{email}</strong> ha sido bloqueada después de 5 intentos de inicio de sesión fallidos.",
                "ipLabel": "Dirección IP",
                "advice": "La cuenta se desbloqueará automáticamente después de 15 minutos. Si cree que es un ataque, contacte inmediatamente con su administrador.",
                "text": "Cuenta {email} bloqueada después de 5 intentos fallidos desde {ip}. Se desbloquea en 15 minutos.",
            },
            "breakGlass": {
                "subject": "[Smart EDMS] ⚠️ Acceso de emergencia por {userEmail}",
                "title": "⚠️ Acceso de emergencia concedido",
                "heading": "Acceso administrativo de emergencia concedido",
                "alert": "Se ha concedido a <strong>{userEmail}</strong> acceso administrativo de emergencia.",
                "userLabel": "Usuario",
                "reasonLabel": "Motivo",
                "expiresLabel": "Expira",
                "reviewAdvice": "Todas las acciones realizadas durante esta sesión se registran en la auditoría con atribución de emergencia. Revise la pista de auditoría después de que expire la sesión.",
                "text": "Acceso de emergencia concedido a {userEmail}. Motivo: {reason}. Expira: {expiresAt}. Revise la pista de auditoría.",
            },
            "workflowAssigned": {
                "subject": "[Smart EDMS] Aprobación solicitada: {documentTitle}",
                "title": "Aprobación solicitada",
                "heading": "Tiene un documento para aprobar",
                "body": "Se le ha asignado una aprobación en Smart EDMS.",
                "documentLabel": "Documento",
                "workflowLabel": "Flujo de trabajo",
                "cta": "Revisar y aprobar",
                "text": "Aprobación solicitada para \"{documentTitle}\" ({workflowName}).\n\nRevisar: {workflowUrl}",
            },
            "shareNotification": {
                "subject": "[Smart EDMS] Documento compartido: {documentTitle}",
                "title": "Documento compartido con usted",
                "heading": "Se ha compartido un documento con usted",
                "body": "<strong>{sharedBy}</strong> ha compartido un documento con usted en Smart EDMS.",
                "documentLabel": "Documento",
                "cta": "Ver documento",
                "expiresNote": "Este enlace de compartir expira el {expiresAt}.",
                "text": "{sharedBy} ha compartido \"{documentTitle}\" con usted.\n\nVer: {shareUrl}",
            },
            "dispositionApproval": {
                "subject": "[Smart EDMS] Aprobación de disposición: {documentTitle}",
                "title": "Aprobación de disposición requerida",
                "heading": "Aprobación de disposición requerida",
                "alert": "Un documento está pendiente de disposición <strong>{actionLabel}</strong> y requiere su aprobación.",
                "documentLabel": "Documento",
                "actionLabel": "Acción",
                "cta": "Revisar disposición",
                "text": "Aprobación de disposición requerida para \"{documentTitle}\" (acción: {action}).\n\nRevisar: {url}",
                "actions": {
                    "delete": "Eliminar",
                    "archive": "Archivar",
                    "review": "Revisar",
                },
            },
            "passwordReset": {
                "subject": "[Smart EDMS] Restablecimiento de contraseña",
                "title": "Restablecimiento de contraseña",
                "heading": "Solicitud de restablecimiento de contraseña",
                "body": "Hemos recibido una solicitud para restablecer su contraseña de Smart EDMS.",
                "alert": "Este enlace expira en 30 minutos. Si no solicitó esto, puede ignorar este correo de forma segura.",
                "cta": "Restablecer contraseña",
                "text": "Solicitud de restablecimiento de contraseña.\n\nRestablezca su contraseña: {resetUrl}\n\nEste enlace expira en 30 minutos.",
            },
        }
    },
    "de": {
        "emails": {
            "common": {
                "appName": "Smart EDMS",
                "tagline": "Sichere Plattform für Dokumenten-Governance",
                "footer": "Dies ist eine automatisierte Nachricht. Nicht antworten.",
                "footerAddress": "Smart EDMS — Sichere Plattform für Dokumenten-Governance",
                "unsubscribe": "Benachrichtigungseinstellungen verwalten",
                "privacyNotice": "Sie erhalten diese E-Mail, weil Sie ein Smart EDMS-Konto haben. Wenn Sie dies für einen Fehler halten, wenden Sie sich an Ihren Administrator.",
                "autoGenerated": "Automatisierte Nachricht — bitte nicht direkt auf diese E-Mail antworten.",
                "linkHelpText": "Wenn die Schaltfläche oben nicht funktioniert, kopieren Sie diesen Link und fügen Sie ihn in Ihren Browser ein:",
                "expiresIn": "Dieser Link läuft in {duration} ab.",
                "viewInBrowser": "Im Browser anzeigen",
            },
            "invitation": {
                "subject": "Einladung zu {tenantName} auf Smart EDMS",
                "title": "Sie sind eingeladen",
                "heading": "Sie wurden zu {tenantName} eingeladen",
                "body": "<strong>{inviterEmail}</strong> hat Sie eingeladen, Smart EDMS bei <strong>{tenantName}</strong> beizutreten.",
                "cta": "Einladung annehmen",
                "expiresNote": "Ihre Einladung läuft in 7 Tagen ab.",
                "welcome": "Smart EDMS ist eine sichere Plattform für elektronisches Dokumentenmanagement mit Klassifizierung, Workflow, Aufbewahrung und Audit-Trail.",
            },
            "failedLogin": {
                "subject": "[Smart EDMS] {count} fehlgeschlagene Anmeldeversuche",
                "title": "Fehlgeschlagene Anmeldeversuche",
                "heading": "Fehlgeschlagene Anmeldeversuche auf Ihrem Konto",
                "alert": "Es wurden <strong>{count}</strong> fehlgeschlagene(n) Anmeldeversuch(e) auf Ihrem Smart EDMS-Konto aufgezeichnet.",
                "ipLabel": "IP-Adresse",
                "advice": "Wenn Sie das nicht waren, ändern Sie sofort Ihr Passwort und aktivieren Sie MFA, falls noch nicht geschehen.",
                "lockWarning": "Ihr Konto wird nach 5 fehlgeschlagenen Versuchen vorübergehend gesperrt.",
                "text": "{count} fehlgeschlagene Anmeldeversuche von IP {ip}.\n\nWenn Sie das nicht waren, ändern Sie Ihr Passwort und aktivieren Sie MFA.",
            },
            "accountLocked": {
                "subject": "[Smart EDMS] Konto gesperrt: {email}",
                "title": "Konto gesperrt",
                "heading": "Konto gesperrt",
                "alert": "Das Konto <strong>{email}</strong> wurde nach 5 fehlgeschlagenen Anmeldeversuchen gesperrt.",
                "ipLabel": "IP-Adresse",
                "advice": "Das Konto wird nach 15 Minuten automatisch entsperrt. Wenn Sie glauben, dass dies ein Angriff ist, wenden Sie sich sofort an Ihren Administrator.",
                "text": "Konto {email} nach 5 fehlgeschlagenen Anmeldungen von {ip} gesperrt. Automatische Entsperrung in 15 Minuten.",
            },
            "breakGlass": {
                "subject": "[Smart EDMS] ⚠️ Notfallzugriff durch {userEmail}",
                "title": "⚠️ Notfallzugriff gewährt",
                "heading": "Notfall-Administratorzugriff gewährt",
                "alert": "<strong>{userEmail}</strong> wurde Notfall-Administratorzugriff gewährt.",
                "userLabel": "Benutzer",
                "reasonLabel": "Grund",
                "expiresLabel": "Läuft ab",
                "reviewAdvice": "Alle während dieser Sitzung durchgeführten Aktionen werden mit Notfallzugriff-Attributierung im Audit-Protokoll erfasst. Bitte überprüfen Sie den Audit-Trail nach Ablauf der Sitzung.",
                "text": "Notfallzugriff für {userEmail} gewährt. Grund: {reason}. Läuft ab: {expiresAt}. Audit-Trail überprüfen.",
            },
            "workflowAssigned": {
                "subject": "[Smart EDMS] Freigabe angefordert: {documentTitle}",
                "title": "Freigabe angefordert",
                "heading": "Sie haben ein Dokument zu genehmigen",
                "body": "Ihnen wurde in Smart EDMS eine Freigabe zugewiesen.",
                "documentLabel": "Dokument",
                "workflowLabel": "Workflow",
                "cta": "Prüfen und genehmigen",
                "text": "Freigabe angefordert für „{documentTitle}“ ({workflowName}).\n\nPrüfen: {workflowUrl}",
            },
            "shareNotification": {
                "subject": "[Smart EDMS] Dokument geteilt: {documentTitle}",
                "title": "Dokument mit Ihnen geteilt",
                "heading": "Ein Dokument wurde mit Ihnen geteilt",
                "body": "<strong>{sharedBy}</strong> hat ein Dokument mit Ihnen auf Smart EDMS geteilt.",
                "documentLabel": "Dokument",
                "cta": "Dokument anzeigen",
                "expiresNote": "Dieser Freigabelink läuft am {expiresAt} ab.",
                "text": "{sharedBy} hat „{documentTitle}“ mit Ihnen geteilt.\n\nAnzeigen: {shareUrl}",
            },
            "dispositionApproval": {
                "subject": "[Smart EDMS] Dispositionsfreigabe: {documentTitle}",
                "title": "Dispositionsfreigabe erforderlich",
                "heading": "Dispositionsfreigabe erforderlich",
                "alert": "Ein Dokument steht zur <strong>{actionLabel}</strong>-Disposition an und erfordert Ihre Freigabe.",
                "documentLabel": "Dokument",
                "actionLabel": "Aktion",
                "cta": "Disposition prüfen",
                "text": "Dispositionsfreigabe erforderlich für „{documentTitle}“ (Aktion: {action}).\n\nPrüfen: {url}",
                "actions": {
                    "delete": "Löschen",
                    "archive": "Archivieren",
                    "review": "Prüfen",
                },
            },
            "passwordReset": {
                "subject": "[Smart EDMS] Passwort zurücksetzen",
                "title": "Passwort zurücksetzen",
                "heading": "Anfrage zum Zurücksetzen des Passworts",
                "body": "Wir haben eine Anfrage erhalten, Ihr Smart EDMS-Passwort zurückzusetzen.",
                "alert": "Dieser Link läuft in 30 Minuten ab. Wenn Sie dies nicht angefordert haben, können Sie diese E-Mail sicher ignorieren.",
                "cta": "Passwort zurücksetzen",
                "text": "Anfrage zum Zurücksetzen des Passworts.\n\nPasswort zurücksetzen: {resetUrl}\n\nDieser Link läuft in 30 Minuten ab.",
            },
        }
    },
}

# ------------------------------------------------------------------
#  NOTIFICATION BUNDLES — 16 templates x 5 locales
# ------------------------------------------------------------------

NOTIFICATIONS = {
    "en": {
        "notifications": {
            "security.failed_login": {
                "title": "Failed login attempt",
                "body": "There were {count} failed login attempts on your account from IP {ip}.",
            },
            "security.account_locked": {
                "title": "Account locked",
                "body": "Account {email} was locked after 5 failed login attempts from IP {ip}.",
            },
            "workflow.assigned": {
                "title": "Approval requested",
                "body": "You have been assigned to approve \"{docTitle}\" ({wfName}).",
            },
            "workflow.escalated": {
                "title": "Escalated approval",
                "body": "Approval for \"{docTitle}\" was escalated to you.",
            },
            "workflow.overdue": {
                "title": "Overdue approval",
                "body": "Approval for \"{docTitle}\" is overdue and has no escalation target.",
            },
            "workflow.reminder": {
                "title": "Approval due soon",
                "body": "Your approval for \"{docTitle}\" is due {dueAt}.",
            },
            "workflow.completed": {
                "title": "Workflow completed",
                "body": "Workflow \"{wfName}\" for \"{docTitle}\" is complete.",
            },
            "workflow.rejected": {
                "title": "Workflow rejected",
                "body": "Workflow \"{wfName}\" for \"{docTitle}\" was rejected by {rejector}.",
            },
            "share.created": {
                "title": "Document shared",
                "body": "{sharedBy} shared \"{docTitle}\" with {recipient}.",
            },
            "share.received": {
                "title": "Document shared with you",
                "body": "{sharedBy} shared \"{docTitle}\" with you.",
            },
            "share.expiring": {
                "title": "Share link expiring soon",
                "body": "The share link for \"{docTitle}\" expires {expiresAt}.",
            },
            "share.revoked": {
                "title": "Share link revoked",
                "body": "A share link for \"{docTitle}\" was revoked.",
            },
            "breakglass.alert": {
                "title": "⚠️ Break-glass access granted",
                "body": "{email} was granted emergency admin access. Reason: {reason}",
            },
            "security.anomaly_detected": {
                "title": "Security anomaly detected",
                "body": "{description}",
            },
            "policy.violation": {
                "title": "Policy violation detected",
                "body": "{actor} was denied {action} on {resource}. Reason: {reason}",
            },
            "system.health_degraded": {
                "title": "⚠️ System health degraded",
                "body": "Health check found issues: {issues}",
            },
            "document.comment": {
                "title": "New comment on your document",
                "body": "{author} commented on \"{docTitle}\"",
            },
            "document.uploaded": {
                "title": "Document uploaded",
                "body": "\"{docTitle}\" was uploaded by {author}.",
            },
            "document.version_created": {
                "title": "New document version",
                "body": "Version {version} of \"{docTitle}\" was created by {author}.",
            },
            "recertification.assigned": {
                "title": "Access recertification campaign assigned",
                "body": "{count} user(s) require access recertification for \"{name}\".",
            },
            "recertification.revoked": {
                "title": "Access revoked",
                "body": "Your access was revoked during recertification campaign \"{name}\".",
            },
            "dual_control.request": {
                "title": "Dual-control approval required",
                "body": "{email} requested approval for: {action}",
            },
            "disposition.pending": {
                "title": "Disposition approval required",
                "body": "Document \"{docTitle}\" is pending {action} disposition.",
            },
            "disposition.completed": {
                "title": "Disposition completed",
                "body": "Document \"{docTitle}\" was {action}.",
            },
            "legal_hold.applied": {
                "title": "Legal hold applied",
                "body": "A legal hold was applied to \"{docTitle}\".",
            },
            "legal_hold.released": {
                "title": "Legal hold released",
                "body": "The legal hold on \"{docTitle}\" was released.",
            },
        }
    },
    "fr": {
        "notifications": {
            "security.failed_login": {
                "title": "Tentative de connexion échouée",
                "body": "Il y a eu {count} tentatives de connexion échouées sur votre compte depuis l'IP {ip}.",
            },
            "security.account_locked": {
                "title": "Compte verrouillé",
                "body": "Le compte {email} a été verrouillé après 5 tentatives de connexion échouées depuis l'IP {ip}.",
            },
            "workflow.assigned": {
                "title": "Approbation demandée",
                "body": "Vous avez été assigné à approuver « {docTitle} » ({wfName}).",
            },
            "workflow.escalated": {
                "title": "Approbation escaladée",
                "body": "L'approbation pour « {docTitle} » vous a été escaladée.",
            },
            "workflow.overdue": {
                "title": "Approbation en retard",
                "body": "L'approbation pour « {docTitle} » est en retard et n'a pas de cible d'escalade.",
            },
            "workflow.reminder": {
                "title": "Approbation à échéance",
                "body": "Votre approbation pour « {docTitle} » est due {dueAt}.",
            },
            "workflow.completed": {
                "title": "Flux de travail terminé",
                "body": "Le flux « {wfName} » pour « {docTitle} » est terminé.",
            },
            "workflow.rejected": {
                "title": "Flux de travail rejeté",
                "body": "Le flux « {wfName} » pour « {docTitle} » a été rejeté par {rejector}.",
            },
            "share.created": {
                "title": "Document partagé",
                "body": "{sharedBy} a partagé « {docTitle} » avec {recipient}.",
            },
            "share.received": {
                "title": "Document partagé avec vous",
                "body": "{sharedBy} a partagé « {docTitle} » avec vous.",
            },
            "share.expiring": {
                "title": "Lien de partage expirant bientôt",
                "body": "Le lien de partage pour « {docTitle} » expire {expiresAt}.",
            },
            "share.revoked": {
                "title": "Lien de partage révoqué",
                "body": "Un lien de partage pour « {docTitle} » a été révoqué.",
            },
            "breakglass.alert": {
                "title": "⚠️ Accès d'urgence accordé",
                "body": "{email} a reçu un accès administrateur d'urgence. Motif : {reason}",
            },
            "security.anomaly_detected": {
                "title": "Anomalie de sécurité détectée",
                "body": "{description}",
            },
            "policy.violation": {
                "title": "Violation de politique détectée",
                "body": "{actor} s'est vu refuser {action} sur {resource}. Motif : {reason}",
            },
            "system.health_degraded": {
                "title": "⚠️ Santé du système dégradée",
                "body": "Le contrôle de santé a trouvé des problèmes : {issues}",
            },
            "document.comment": {
                "title": "Nouveau commentaire sur votre document",
                "body": "{author} a commenté « {docTitle} »",
            },
            "document.uploaded": {
                "title": "Document téléversé",
                "body": "« {docTitle} » a été téléversé par {author}.",
            },
            "document.version_created": {
                "title": "Nouvelle version de document",
                "body": "La version {version} de « {docTitle} » a été créée par {author}.",
            },
            "recertification.assigned": {
                "title": "Campagne de recertification d'accès assignée",
                "body": "{count} utilisateur(s) nécessitent une recertification d'accès pour « {name} ».",
            },
            "recertification.revoked": {
                "title": "Accès révoqué",
                "body": "Votre accès a été révoqué lors de la campagne de recertification « {name} ».",
            },
            "dual_control.request": {
                "title": "Approbation à double contrôle requise",
                "body": "{email} a demandé une approbation pour : {action}",
            },
            "disposition.pending": {
                "title": "Approbation de disposition requise",
                "body": "Le document « {docTitle} » est en attente de disposition {action}.",
            },
            "disposition.completed": {
                "title": "Disposition terminée",
                "body": "Le document « {docTitle} » a été {action}.",
            },
            "legal_hold.applied": {
                "title": "Conservation légale appliquée",
                "body": "Une conservation légale a été appliquée à « {docTitle} ».",
            },
            "legal_hold.released": {
                "title": "Conservation légale levée",
                "body": "La conservation légale sur « {docTitle} » a été levée.",
            },
        }
    },
    "ar": {
        "notifications": {
            "security.failed_login": {
                "title": "محاولة دخول فاشلة",
                "body": "كانت هناك {count} محاولات دخول فاشلة على حسابك من IP {ip}.",
            },
            "security.account_locked": {
                "title": "تم قفل الحساب",
                "body": "تم قفل الحساب {email} بعد 5 محاولات دخول فاشلة من IP {ip}.",
            },
            "workflow.assigned": {
                "title": "طلب موافقة",
                "body": "تم تعيينك للموافقة على \"{docTitle}\" ({wfName}).",
            },
            "workflow.escalated": {
                "title": "موافقة مُصعَّدة",
                "body": "تم تصعيد الموافقة على \"{docTitle}\" إليك.",
            },
            "workflow.overdue": {
                "title": "موافقة متأخرة",
                "body": "الموافقة على \"{docTitle}\" متأخرة وليس لها هدف تصعيد.",
            },
            "workflow.reminder": {
                "title": "موافقة مستحقة قريباً",
                "body": "موافقتك على \"{docTitle}\" مستحقة {dueAt}.",
            },
            "workflow.completed": {
                "title": "اكتمل سير العمل",
                "body": "اكتمل سير العمل \"{wfName}\" لـ \"{docTitle}\".",
            },
            "workflow.rejected": {
                "title": "تم رفض سير العمل",
                "body": "تم رفض سير العمل \"{wfName}\" لـ \"{docTitle}\" بواسطة {rejector}.",
            },
            "share.created": {
                "title": "تمت مشاركة مستند",
                "body": "شارك {sharedBy} \"{docTitle}\" مع {recipient}.",
            },
            "share.received": {
                "title": "تمت مشاركة مستند معك",
                "body": "شارك {sharedBy} \"{docTitle}\" معك.",
            },
            "share.expiring": {
                "title": "رابط المشاركة ينتهي قريباً",
                "body": "رابط المشاركة لـ \"{docTitle}\" ينتهي {expiresAt}.",
            },
            "share.revoked": {
                "title": "تم إلغاء رابط المشاركة",
                "body": "تم إلغاء رابط مشاركة لـ \"{docTitle}\".",
            },
            "breakglass.alert": {
                "title": "⚠️ تم منح وصول طارئ",
                "body": "تم منح {email} وصولاً إدارياً طارئاً. السبب: {reason}",
            },
            "security.anomaly_detected": {
                "title": "تم اكتشاف شذوذ أمني",
                "body": "{description}",
            },
            "policy.violation": {
                "title": "تم اكتشاف انتهاك سياسة",
                "body": "تم رفض {action} على {resource} بواسطة {actor}. السبب: {reason}",
            },
            "system.health_degraded": {
                "title": "⚠️ تدهور صحة النظام",
                "body": "وجد فحص الصحة مشاكل: {issues}",
            },
            "document.comment": {
                "title": "تعليق جديد على مستندك",
                "body": "علّق {author} على \"{docTitle}\"",
            },
            "document.uploaded": {
                "title": "تم رفع مستند",
                "body": "تم رفع \"{docTitle}\" بواسطة {author}.",
            },
            "document.version_created": {
                "title": "إصدار مستند جديد",
                "body": "تم إنشاء الإصدار {version} من \"{docTitle}\" بواسطة {author}.",
            },
            "recertification.assigned": {
                "title": "تم تعيين حملة إعادة شهادة الوصول",
                "body": "{count} مستخدم(ين) يتطلبون إعادة شهادة الوصول لـ \"{name}\".",
            },
            "recertification.revoked": {
                "title": "تم إلغاء الوصول",
                "body": "تم إلغاء وصولك خلال حملة إعادة الشهادة \"{name}\".",
            },
            "dual_control.request": {
                "title": "مطلوب موافقة الرقابة المزدوجة",
                "body": "طلب {email} الموافقة على: {action}",
            },
            "disposition.pending": {
                "title": "مطلوب موافقة على التصرف",
                "body": "المستند \"{docTitle}\" في انتظار تصرف {action}.",
            },
            "disposition.completed": {
                "title": "اكتمل التصرف",
                "body": "تم {action} المستند \"{docTitle}\".",
            },
            "legal_hold.applied": {
                "title": "تم تطبيق تعليق قانوني",
                "body": "تم تطبيق تعليق قانوني على \"{docTitle}\".",
            },
            "legal_hold.released": {
                "title": "تم رفع التعليق القانوني",
                "body": "تم رفع التعليق القانوني عن \"{docTitle}\".",
            },
        }
    },
    "es": {
        "notifications": {
            "security.failed_login": {
                "title": "Intento de inicio de sesión fallido",
                "body": "Hubo {count} intentos de inicio de sesión fallidos en su cuenta desde IP {ip}.",
            },
            "security.account_locked": {
                "title": "Cuenta bloqueada",
                "body": "La cuenta {email} fue bloqueada después de 5 intentos fallidos desde IP {ip}.",
            },
            "workflow.assigned": {
                "title": "Aprobación solicitada",
                "body": "Se le ha asignado aprobar \"{docTitle}\" ({wfName}).",
            },
            "workflow.escalated": {
                "title": "Aprobación escalada",
                "body": "La aprobación de \"{docTitle}\" fue escalada a usted.",
            },
            "workflow.overdue": {
                "title": "Aprobación vencida",
                "body": "La aprobación de \"{docTitle}\" está vencida y no tiene destino de escalado.",
            },
            "workflow.reminder": {
                "title": "Aprobación próxima a vencer",
                "body": "Su aprobación de \"{docTitle}\" vence {dueAt}.",
            },
            "workflow.completed": {
                "title": "Flujo de trabajo completado",
                "body": "El flujo \"{wfName}\" para \"{docTitle}\" está completo.",
            },
            "workflow.rejected": {
                "title": "Flujo de trabajo rechazado",
                "body": "El flujo \"{wfName}\" para \"{docTitle}\" fue rechazado por {rejector}.",
            },
            "share.created": {
                "title": "Documento compartido",
                "body": "{sharedBy} compartió \"{docTitle}\" con {recipient}.",
            },
            "share.received": {
                "title": "Documento compartido con usted",
                "body": "{sharedBy} compartió \"{docTitle}\" con usted.",
            },
            "share.expiring": {
                "title": "Enlace de compartir expirando pronto",
                "body": "El enlace de compartir para \"{docTitle}\" expira {expiresAt}.",
            },
            "share.revoked": {
                "title": "Enlace de compartir revocado",
                "body": "Se revocó un enlace de compartir para \"{docTitle}\".",
            },
            "breakglass.alert": {
                "title": "⚠️ Acceso de emergencia concedido",
                "body": "{email} recibió acceso administrativo de emergencia. Motivo: {reason}",
            },
            "security.anomaly_detected": {
                "title": "Anomalía de seguridad detectada",
                "body": "{description}",
            },
            "policy.violation": {
                "title": "Violación de política detectada",
                "body": "{actor} tuvo denegado {action} en {resource}. Motivo: {reason}",
            },
            "system.health_degraded": {
                "title": "⚠️ Salud del sistema degradada",
                "body": "El control de salud encontró problemas: {issues}",
            },
            "document.comment": {
                "title": "Nuevo comentario en su documento",
                "body": "{author} comentó en \"{docTitle}\"",
            },
            "document.uploaded": {
                "title": "Documento subido",
                "body": "\"{docTitle}\" fue subido por {author}.",
            },
            "document.version_created": {
                "title": "Nueva versión del documento",
                "body": "La versión {version} de \"{docTitle}\" fue creada por {author}.",
            },
            "recertification.assigned": {
                "title": "Campaña de recertificación de acceso asignada",
                "body": "{count} usuario(s) requieren recertificación de acceso para \"{name}\".",
            },
            "recertification.revoked": {
                "title": "Acceso revocado",
                "body": "Su acceso fue revocado durante la campaña de recertificación \"{name}\".",
            },
            "dual_control.request": {
                "title": "Aprobación de doble control requerida",
                "body": "{email} solicitó aprobación para: {action}",
            },
            "disposition.pending": {
                "title": "Aprobación de disposición requerida",
                "body": "El documento \"{docTitle}\" está pendiente de disposición {action}.",
            },
            "disposition.completed": {
                "title": "Disposición completada",
                "body": "El documento \"{docTitle}\" fue {action}.",
            },
            "legal_hold.applied": {
                "title": "Retención legal aplicada",
                "body": "Se aplicó una retención legal a \"{docTitle}\".",
            },
            "legal_hold.released": {
                "title": "Retención legal liberada",
                "body": "La retención legal sobre \"{docTitle}\" fue liberada.",
            },
        }
    },
    "de": {
        "notifications": {
            "security.failed_login": {
                "title": "Fehlgeschlagener Anmeldeversuch",
                "body": "Es gab {count} fehlgeschlagene Anmeldeversuche auf Ihrem Konto von IP {ip}.",
            },
            "security.account_locked": {
                "title": "Konto gesperrt",
                "body": "Konto {email} wurde nach 5 fehlgeschlagenen Anmeldeversuchen von IP {ip} gesperrt.",
            },
            "workflow.assigned": {
                "title": "Freigabe angefordert",
                "body": "Ihnen wurde die Freigabe von „{docTitle}“ ({wfName}) zugewiesen.",
            },
            "workflow.escalated": {
                "title": "Eskalierte Freigabe",
                "body": "Die Freigabe für „{docTitle}“ wurde an Sie eskaliert.",
            },
            "workflow.overdue": {
                "title": "Überfällige Freigabe",
                "body": "Die Freigabe für „{docTitle}“ ist überfällig und hat kein Eskalationsziel.",
            },
            "workflow.reminder": {
                "title": "Freigabe fällt bald an",
                "body": "Ihre Freigabe für „{docTitle}“ ist am {dueAt} fällig.",
            },
            "workflow.completed": {
                "title": "Workflow abgeschlossen",
                "body": "Workflow „{wfName}“ für „{docTitle}“ ist abgeschlossen.",
            },
            "workflow.rejected": {
                "title": "Workflow abgelehnt",
                "body": "Workflow „{wfName}“ für „{docTitle}“ wurde von {rejector} abgelehnt.",
            },
            "share.created": {
                "title": "Dokument geteilt",
                "body": "{sharedBy} hat „{docTitle}“ mit {recipient} geteilt.",
            },
            "share.received": {
                "title": "Dokument mit Ihnen geteilt",
                "body": "{sharedBy} hat „{docTitle}“ mit Ihnen geteilt.",
            },
            "share.expiring": {
                "title": "Freigabelink läuft bald ab",
                "body": "Der Freigabelink für „{docTitle}“ läuft am {expiresAt} ab.",
            },
            "share.revoked": {
                "title": "Freigabelink widerrufen",
                "body": "Ein Freigabelink für „{docTitle}“ wurde widerrufen.",
            },
            "breakglass.alert": {
                "title": "⚠️ Notfallzugriff gewährt",
                "body": "{email} erhielt Notfall-Administratorzugriff. Grund: {reason}",
            },
            "security.anomaly_detected": {
                "title": "Sicherheitsanomalie erkannt",
                "body": "{description}",
            },
            "policy.violation": {
                "title": "Richtlinienverletzung erkannt",
                "body": "{actor} wurde {action} auf {resource} verweigert. Grund: {reason}",
            },
            "system.health_degraded": {
                "title": "⚠️ Systemzustand degradiert",
                "body": "Gesundheitsprüfung fand Probleme: {issues}",
            },
            "document.comment": {
                "title": "Neuer Kommentar zu Ihrem Dokument",
                "body": "{author} hat „{docTitle}“ kommentiert",
            },
            "document.uploaded": {
                "title": "Dokument hochgeladen",
                "body": "„{docTitle}“ wurde von {author} hochgeladen.",
            },
            "document.version_created": {
                "title": "Neue Dokumentversion",
                "body": "Version {version} von „{docTitle}“ wurde von {author} erstellt.",
            },
            "recertification.assigned": {
                "title": "Zugriffs-Rezertifizierungskampagne zugewiesen",
                "body": "{count} Benutzer benötigen Zugriffs-Rezertifizierung für „{name}“.",
            },
            "recertification.revoked": {
                "title": "Zugriff widerrufen",
                "body": "Ihr Zugriff wurde während der Rezertifizierungskampagne „{name}“ widerrufen.",
            },
            "dual_control.request": {
                "title": "Doppelkontroll-Freigabe erforderlich",
                "body": "{email} forderte Freigabe für: {action}",
            },
            "disposition.pending": {
                "title": "Dispositionsfreigabe erforderlich",
                "body": "Dokument „{docTitle}“ steht zur {action}-Disposition an.",
            },
            "disposition.completed": {
                "title": "Disposition abgeschlossen",
                "body": "Dokument „{docTitle}“ wurde {action}.",
            },
            "legal_hold.applied": {
                "title": "Rechtliche Aufbewahrung angewendet",
                "body": "Eine rechtliche Aufbewahrung wurde auf „{docTitle}“ angewendet.",
            },
            "legal_hold.released": {
                "title": "Rechtliche Aufbewahrung aufgehoben",
                "body": "Die rechtliche Aufbewahrung für „{docTitle}“ wurde aufgehoben.",
            },
        }
    },
}


def merge_into(existing: dict, addition: dict) -> dict:
    """Deep-merge `addition` into `existing` (addition wins on conflict)."""
    for k, v in addition.items():
        if isinstance(v, dict) and isinstance(existing.get(k), dict):
            merge_into(existing[k], v)
        else:
            existing[k] = v
    return existing


def main():
    for locale in ("en", "fr", "ar", "es", "de"):
        path = MESSAGES_DIR / f"{locale}.json"
        if not path.exists():
            print(f"[skip] {path} does not exist")
            continue
        with open(path, "r", encoding="utf-8") as f:
            data = json.load(f)

        # Merge emails + notifications into the bundle
        addition = {**EMAILS[locale], **NOTIFICATIONS[locale]}
        before_keys = set(data.keys())
        merge_into(data, addition)
        after_keys = set(data.keys())

        with open(path, "w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, indent=2)
            f.write("\n")

        new_keys = after_keys - before_keys
        print(f"[ok] {locale}: added {len(new_keys)} top-level keys ({', '.join(sorted(new_keys))})")

    print("\nDone. Run `bun run check:translations` to verify completeness.")


if __name__ == "__main__":
    sys.exit(main())
